# 參考來源 https://docs.gitlab.com/ee/user/packages/container_registry/
#image: docker:stable

# 使用docker in docker 必要的 services 區塊
services:
  - name: docker:dind
    alias: docker

# 全域變數宣告
#variables:
#  DOCKER_HOST: tcp://docker:2376
#  DOCKER_TLS_CERTDIR: "/certs"
#  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build
#  - test  

docker-build:
  # 可以不指定，會用services區塊指定的image
  image: docker:dind
  stage: build
  #environment:
  #  name: review/$CI_COMMIT_REF_NAME
  tags:
    - andyhuang-lab
  before_script:
    - |
      ls -al
      cat /etc/resolv.conf
      cat /etc/hosts
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD

  script:
    # 有錯誤就離開 ，$CI_REGISTRY_IMAGE $CI_REGISTRY  是系統提供的 
    - set -eux && docker logon -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  
    #- set -eux && docker login -u ${GITLAB_USER} -p ${GITLAB_TOKEN} $CI_REGISTRY
    #- set -ex && docker build -t $CI_REGISTRY_IMAGE .
    #- set -ex && docker push $CI_REGISTRY_IMAGE

#ubuntu-build:
#  # 需指定，否則會使用services區塊指定的image造成pipeline錯誤
#  image: ubuntu:20.04
#  stage: test
#  #environment:
#  #  name: review/$CI_COMMIT_REF_NAME
#  tags:
#    - andyhuang-lab
#
#  script:
#    - echo $HOSTNAME
#    - pwd
#    - ls -al
#    - apt-get update
