variables:
  # When using dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket.
  DOCKER_HOST: tcp://docker:2376
  DOCKER_CERT_PATH: /certs/client
stages:
  - build
  
docker-build:
  image: docker:dind
  stage: build
  tags:
    - andyhuang-lab
  before_script:
    - ls -al
    - cat /etc/resolv.conf
    - cat /etc/hosts


  script:
    - docker build -t ubuntu .
    #- docker push nexus-beta.gamesoft-tech.com/jenkins-agent:latest

