#image: docker:stable

# 使用docker in docker 必要的 services 區塊
services:
  - name: docker:dind
    alias: docker

#variables:
#  DOCKER_HOST: tcp://docker:2376
#  DOCKER_TLS_CERTDIR: "/certs"
#  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build
  - test  

docker-build:
  image: docker:dind
  stage: build
  #environment:
  #  name: review/$CI_COMMIT_REF_NAME
  tags:
    - andyhuang-lab
  before_script:
    - ls -al
    - cat /etc/resolv.conf
    - cat /etc/hosts

  script:
    - echo $HOSTNAME
    - pwd
    - docker pull busybox
    - docker images

ubuntu-build:
  image: ubuntu:20.04
  stage: test
  #environment:
  #  name: review/$CI_COMMIT_REF_NAME
  tags:
    - andyhuang-lab

  script:
    - echo $HOSTNAME
    - pwd
    - ls -al
    - docker images
