image: docker:stable

# 使用docker in docker 必要的 services 區塊
services:
  - name: docker:dind
    alias: docker

#variables:
  #DOCKER_DRIVER: overlay2

stages:
  - build
  
docker-build:
  #image: docker:dind
  stage: build
  #environment:
  #  name: review/$CI_COMMIT_REF_NAME
  tags:
    - andyhuang-lab
  before_script:
    - ls -al
    - cat /etc/resolv.conf
    - cat /etc/hosts

  script:
    - docker build -t ubuntu .

docker-build:
  image: ubuntu:20.04
  stage: build
  #environment:
  #  name: review/$CI_COMMIT_REF_NAME
  tags:
    - andyhuang-lab

  script:
    - lsb_release -a
